platform-events/main/default/objects/Opportunity/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

platform-events/main/default/objects/OpportunityStatus__e/OpportunityStatus__e.object-meta.xml
<CustomObject>
    <label>Opportunity Status</label>
    <pluralLabel>Opportunities Status</pluralLabel>
</CustomObject>

platform-events/main/default/objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPersons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

platform-events/main/default/classes/Opportunityz.cls
public class Opportunityz {
    public String name;
    public Id id;
    public Id salesPersonId;
    public String salesPersonName;
    public Id accountId;
    public String accountName;
    public Date closeDate;
    public String stageName;
    public List<OpportunityLineItemz> items;

    private transient OpportunityRepository repository;
    
    public Opportunityz(){
		this.repository = new OpportunityRepository(); 
        this.items = new List<OpportunityLineItemz>();
    }
    
    public Opportunityz(Id opportunityId) {
        this();
        buildWith(opportunityId);
    }
    
    public Opportunityz(Opportunity record) {
        this();
        buildWith(record);
    }
    
    public Opportunityz buildWith(Opportunity record) {
        this.id = record.Id;
        this.name = record.Name;
        this.salesPersonId = record.Salesperson__c;
        this.salesPersonName = record.Salesperson__r.Name;
        this.accountId = record.AccountId;
        this.accountName = record.Account.Name;
        this.closeDate = record.CloseDate;
        this.stageName = record.StageName;

        for (OpportunityLineItem item : record.OpportunityLineItems) {
            this.items.add(new OpportunityLineItemz(item));
        }
            
        return this;
    }

    public Opportunityz buildWith(Id opportunityId) {
        return buildWith(this.repository.findById(opportunityId));
    }
    
    public Opportunityz dispatch() {
        OpportunityStatus__e evt = new OpportunityStatus__e();
        evt.Payload__c = JSON.serialize(this);
        EventBus.publish(evt);
        return null;
    }
    
}